services:
  build:
    context: ./
  back:
    image: nodejs-back
    container_name: back
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./back:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

