openapi: 3.0.3
info:
  title: Roles API
  version: 1.0.0
  description: API Test

servers:
  - url: https://test-ia.duckdns.org/api

paths:
  /users:
    get:
      summary: Create a new user
      description: Create a new user with email, firstname, and lastname
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - firstname
                - lastname
                - role
              properties:
                email:
                  type: string
                  format: email
                firstname:
                  type: string
                lastname:
                  type: string
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  email:
                    type: string
                    format: email
                  firstname:
                    type: string
                  lastname:
                    type: string
                  __v:
                    type: integer
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
